### ISSUE TITLE
status: 404 when calling the billing API

### ISSUE THREAD

**Issue by christianherweg0807** [NickLiffen/ghas-licence#116]
Today I tried to identify unused licenses in our organization and got the following error: 

```Run nickliffen/ghas-licence@v1.1.0
(node:1749) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/nickliffen/ghas-licence/v1.1.0/dist/index.js:7774:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async query (/home/runner/work/_actions/nickliffen/ghas-licence/v1.1.0/dist/index.js:69282:16)
    at async billing (/home/runner/work/_actions/nickliffen/ghas-licence/v1.1.0/dist/index.js:69297:23)
    at async run (/home/runner/work/_actions/nickliffen/ghas-licence/v1.1.0/dist/index.js:69223:33)
    at async main (/home/runner/work/_actions/nickliffen/ghas-licence/v1.1.0/dist/index.js:68897:22) {
  status: 404,
  response: {
    url: 'https://api.github.com/orgs/otto-ec/settings/billing/advanced-security?per_page=100&page=1',
    status: 404,```

**Comment by christianherweg0807** [comment]
@NickLiffen Any idea?

**Comment by NickLiffen** [comment]
Hey @christianherweg0807 👋 

Really sorry only just seeing this 😢 Let me look at this now 🙇

**Comment by NickLiffen** [comment]
Just to share back I have been able to replicate it:

```
Default image and other options can be changed manually in ~/.actrc (please refer to https://github.com/nektos/act#configuration for additional information about file structure) Medium
[Manual Testing - GHAS Licence Checker/dispatch] 🚀  Start image=catthehacker/ubuntu:act-20.04
INFO[0002] Parallel tasks (0) below minimum, setting to 1 
[Manual Testing - GHAS Licence Checker/dispatch]   🐳  docker pull image=catthehacker/ubuntu:act-20.04 platform= username= forcePull=true
[Manual Testing - GHAS Licence Checker/dispatch] using DockerAuthConfig authentication for docker pull
INFO[0037] Parallel tasks (0) below minimum, setting to 1 
[Manual Testing - GHAS Licence Checker/dispatch]   🐳  docker create image=catthehacker/ubuntu:act-20.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Manual Testing - GHAS Licence Checker/dispatch]   🐳  docker run image=catthehacker/ubuntu:act-20.04 platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Manual Testing - GHAS Licence Checker/dispatch] ⭐ Run Main Git Checkout
[Manual Testing - GHAS Licence Checker/dispatch]   🐳  docker cp src=/workspaces/ghas-licence/. dst=/workspaces/ghas-licence/github-advanced-security-licence-checker
[Manual Testing - GHAS Licence Checker/dispatch]   ✅  Success - Main Git Checkout
[Manual Testing - GHAS Licence Checker/dispatch] ⭐ Run Main Licence Checker
[Manual Testing - GHAS Licence Checker/dispatch]   🐳  docker exec cmd=[node /workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js] user= workdir=
| ::error ::Error in making billing API Call
[Manual Testing - GHAS Licence Checker/dispatch]   ❗  ::error::Error in making billing API Call
| RequestError [HttpError]: Bad credentials
|     at /workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js:7761:21
|     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
|     at async query (/workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js:36318:16)
|     at async billing (/workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js:36333:23)
|     at async run (/workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js:36259:33)
|     at async main (/workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js:35933:22) {
|   status: 401,
|   response: {
|     url: 'https://api.github.com/orgs/***/settings/billing/advanced-security?per_page=100&page=1',
|     status: 401,
|     headers: {
|       'access-control-allow-origin': '*',
|       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
|       'content-length': '80',
|       'content-security-policy': "default-src 'none'",
|       'content-type': 'application/json; charset=utf-8',
|       date: 'Wed, 29 Nov 2023 14:44:52 GMT',
|       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
|       server: 'GitHub.com',
|       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
|       vary: 'Accept-Encoding, Accept, X-Requested-With',
|       'x-content-type-options': 'nosniff',
|       'x-frame-options': 'deny',
|       'x-github-media-type': 'github.v3; format=json',
|       'x-github-request-id': '0400:7F0C:19DFADC4:1A2E67F7:65674E64',
|       'x-ratelimit-limit': '60',
|       'x-ratelimit-remaining': '59',
|       'x-ratelimit-reset': '1701272692',
|       'x-ratelimit-resource': 'core',
|       'x-ratelimit-used': '1',
|       'x-xss-protection': '0'
|     },
|     data: {
|       message: 'Bad credentials',
|       documentation_url: 'https://docs.github.com/rest'
|     }
|   },
|   request: {
|     method: 'GET',
|     url: 'https://api.github.com/orgs/***/settings/billing/advanced-security?per_page=100&page=1',
|     headers: {
|       accept: 'application/vnd.github.v3+json',
|       'user-agent': 'octokit-action.js/6.0.6 octokit-core.js/5.0.2 Node.js/18.18.2 (linux; x64)',
|       authorization: 'token [REDACTED]'
|     },
|     request: {
|       fetch: [AsyncFunction: customFetch],
|       hook: [Function: bound bound register]
|     }
|   }
| }
[Manual Testing - GHAS Licence Checker/dispatch]   ❌  Failure - Main Licence Checker
[Manual Testing - GHAS Licence Checker/dispatch] exitcode '1': failure
[Manual Testing - GHAS Licence Checker/dispatch] 🏁  Job failed
```

I will now look as to why this isn't working now 🙇

**Comment by NickLiffen** [comment]
Okay I can't replicate this:

```
[Manual Testing - GHAS Licence Checker/dispatch]   ✅  Success - Main Git Checkout
[Manual Testing - GHAS Licence Checker/dispatch] ⭐ Run Main Licence Checker
[Manual Testing - GHAS Licence Checker/dispatch]   🐳  docker exec cmd=[node /workspaces/ghas-licence/github-advanced-security-licence-checker/dist/index.js] user= workdir=
| Firstly, across your: *** organization, there are 122 total GitHub advanced security committers. E.G this is how many seats you are consuming
| Digging into that 122 active committers (seats consumed) number. We found 300 GitHub repositories where an active committer is present/seat is being consumed
| Furthermore, out of them 300 GitHub repositories where an active committer is present. We found 55 GitHub repositories where there is one or greater unique active committer(s) present. E.G unique is defined as only taking up a GitHub Advanced Security seat on that one repository
| As mentioned in the README, repositories with unique active committers are better to target, as disabling GitHub advanced security on them repositories will clean up a licence straight away. They only commit to that one repository; they are not taking up a licence across multiple repositories where you need to disable GitHub advanced security on them all.
| Now, if you was to disable GitHub advanced security on all 55 repositories, you would be saving a total of 57 seats. (Note: 57 may be higher then 55, because one repository may have more then one unique active committer on) 
| Now, if you was to disable GitHub advanced security on all 300 repositories, you would be saving a total of 122 seats. (This should not be possible though as you would be disabling GitHub advanced security on all repositories in your organisation) 
| Now we have found all repositories consuming GitHub advanced security seats, as well as all repositories with unique committers, let us go ahead and run some checks to see which repositories are the most likely inactive.
| Starting artifact upload
```

It seems to work for me, do you have all the right orgs and secrets set?
